AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon S3 trigger that retrieves metadata for the object that has been
  updated.
Resources:
  TimeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: >-
        Outputs the time
      MemorySize: 128
      Timeout: 3
      Environment:
          Variables:
              TIME_ZONE: !Ref timeZoneParam
              ENVIRO: !Ref enviro
      Events:
          MyTimeApi:
              Type: Api
              Properties:
                  Path: /TimeResource
                  Method: GET

Parameters:
    timeZoneParam:
        Type: String
    enviro:
        Type: String
